### ISSUE TITLE
Error: Cannot find any-observable implementation nor global.Observable. when running husky.

### ISSUE THREAD

**Issue by asimqt** [SamVerschueren/stream-to-observable#2]
I'm getting below error when running husky.
```
husky > pre-commit (node v9.3.0)
/Users/user/dev/bloombergquint-node/node_modules/@samverschueren/stream-to-observable/node_modules/any-observable/register.js:29
		throw new Error('Cannot find any-observable implementation nor' +
		^

Error: Cannot find any-observable implementation nor global.Observable. You must install polyfill or call require("any-observable/register") with your preferred implementation, e.g. require("any-observable/register")('rxjs') on application load prior to any require("any-observable").
    at loadImplementation (/Users/user/dev/bloombergquint-node/node_modules/@samverschueren/stream-to-observable/node_modules/any-observable/register.js:29:9)
    at /Users/user/dev/bloombergquint-node/node_modules/@samverschueren/stream-to-observable/node_modules/any-observable/loader.js:30:18
    at Object.<anonymous> (/Users/user/dev/bloombergquint-node/node_modules/@samverschueren/stream-to-observable/node_modules/any-observable/index.js:2:39)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)```

**Comment by SamVerschueren** [comment]
Have you installed RxJS or zen-observable as mentioned in the documentation?

**Comment by vjpr** [comment]
@SamVerschueren You need to upgrade to `any-observable@0.5.1` when `peerDependenciesMeta` [was added](https://github.com/sindresorhus/any-observable/commit/749e5fe40a9a49d4b773fb868c7fce1e2738eec4).

This is currently breaking Cypress for pnpm.

**Comment by m1heng** [comment]
Hi are we going to fix this?

**Comment by JiangWeixian** [comment]
If anyone build with rollup, try

```ts
alias({
  "resolve": [".ts", ".js", ".tsx", ".jsx"],
  "entries": [
    { "find": "any-observable", "replacement": "zen-observable" }
  ]
})
```
